apiVersion: v1
kind: Secret
metadata:
  name: secret01
data:
  URL: ZXhhjdjuhX #Base64 format
  SUB_URL: THGHHskjj #Base64 format
  DOMAIN: DBGGFkuukkjhj #Base64 format
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx07
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret01

