apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cip #cluster ip
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb #Load balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type # network load balancer. By default it will be a classic b
spec:
  type: LoadBalancer
  selector:
    tier: frontend
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#          envFrom:
#            - secretRef:
#                name: secret02