apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2019-06-16T00:12:34Z
  name: test1
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::63378536644:role/oidc-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: 2019-06-16T00:12:34Z
  name: test2
---
apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  serviceAccountName: test1
  containers:
    - name: debug
      image: rkalluru/loaded:centos8
---
apiVersion: v1
kind: Pod
metadata:
  name: test2
spec:
  serviceAccountName: test2
  containers:
    - name: debug
      image: rkalluru/loaded:centos8 #centos7 is the tag, rkalluru/loaded is image
